spring:
  config:
    import: application-secret.yml
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mariadb://localhost:3306/find_pet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
