spring:
  config:
    import: application-secret.yml
  batch:
    job:
      names: hiJob
    jdbc:
      initialize-schema: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/find_pet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
custom:
  api:
    serviceKey:
    shelterDataUrl: http://apis.data.go.kr/1543061/abandonmentPublicSrvc/abandonmentPublic
    animalKindUrl: http://apis.data.go.kr/1543061/abandonmentPublicSrvc/kind
    cityUrl: http://apis.data.go.kr/1543061/abandonmentPublicSrvc/sido
    districtUrl: http://apis.data.go.kr/1543061/abandonmentPublicSrvc/sigungu
  job:
    test: 0/1 * * * * *
    updateAnimal: 0 0/10 * * * *

