spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/find_pet?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
